//! Boa's **`boa_icu_provider`** exports the default data provider used by its `Intl` implementation.
//!
//! # Crate Overview
//! This crate exports the function `buffer`, which contains an extensive dataset of locale data to
//! enable `Intl` functionality in the engine. The set of locales included is precisely the ["modern"]
//! subset of locales in the [Unicode Common Locale Data Repository][cldr].
//!
//! If you need to support the full set of locales, you can check out the [ICU4X guide] about
//! generating custom data providers. Boa supports plugging any [`BufferProvider`]s
//! generated by the tool.
//!
//! ["modern"]: https://github.com/unicode-org/cldr-json/tree/main/cldr-json/cldr-localenames-modern/main
//! [cldr]: https://github.com/unicode-org/
//! [ICU4X guide]: https://github.com/unicode-org/icu4x/blob/main/docs/tutorials/data_management.md
//! [`BufferProvider`]: icu_provider::buf::BufferProvider
#![doc = include_str!("../ABOUT.md")]
#![doc(
    html_logo_url = "https://raw.githubusercontent.com/boa-dev/boa/main/assets/logo_black.svg",
    html_favicon_url = "https://raw.githubusercontent.com/boa-dev/boa/main/assets/logo_black.svg"
)]
#![cfg_attr(not(feature = "std"), no_std)]

extern crate alloc;
use core::fmt::Debug;

use icu_locale::LocaleFallbacker;
use icu_provider::prelude::*;
use icu_provider_adapters::{fallback::LocaleFallbackProvider, fork::MultiForkByMarkerProvider};
use icu_provider_blob::BlobDataProvider;
use once_cell::sync::{Lazy, OnceCell};

/// A buffer provider that is lazily deserialized at the first data request.
///
/// The provider must specify the list of keys it supports, to avoid deserializing the
/// buffer for unknown keys.
struct LazyBufferProvider {
    provider: OnceCell<BlobDataProvider>,
    bytes: &'static [u8],
    valid_markers: &'static [DataMarkerInfo],
}

impl Debug for LazyBufferProvider {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        f.debug_struct("LazyBufferProvider")
            .field("provider", &self.provider)
            .field("bytes", &"[...]")
            .field("valid_keys", &self.valid_markers)
            .finish()
    }
}

impl DynamicDataProvider<BufferMarker> for LazyBufferProvider {
    fn load_data(
        &self,
        marker: DataMarkerInfo,
        req: DataRequest<'_>,
    ) -> Result<DataResponse<BufferMarker>, DataError> {
        if !self.valid_markers.contains(&marker) {
            return Err(DataErrorKind::MarkerNotFound.with_marker(marker));
        }

        let Ok(provider) = self
            .provider
            .get_or_try_init(|| BlobDataProvider::try_new_from_static_blob(self.bytes))
        else {
            return Err(DataErrorKind::Custom.with_str_context("invalid blob data provider"));
        };

        provider.load_data(marker, req)
    }
}

impl DynamicDryDataProvider<BufferMarker> for LazyBufferProvider {
    fn dry_load_data(
        &self,
        marker: DataMarkerInfo,
        req: DataRequest<'_>,
    ) -> Result<DataResponseMetadata, DataError> {
        if !self.valid_markers.contains(&marker) {
            return Err(DataErrorKind::MarkerNotFound.with_marker(marker));
        }

        let Ok(provider) = self
            .provider
            .get_or_try_init(|| BlobDataProvider::try_new_from_static_blob(self.bytes))
        else {
            return Err(DataErrorKind::Custom.with_str_context("invalid blob data provider"));
        };

        provider.dry_load_data(marker, req)
    }
}

/// A macro that creates a [`LazyBufferProvider`] from an icu4x crate.
macro_rules! provider_from_icu_crate {
    ($service:ident) => {
        provider_from_icu_crate!($service, $service::provider::MARKERS)
    };
    ($service:ident, $markers:expr) => {
        pastey::paste! {
            LazyBufferProvider {
                provider: OnceCell::new(),
                bytes: include_bytes!(concat!(
                    env!("CARGO_MANIFEST_DIR"),
                    "/data/",
                    stringify!($service),
                    ".postcard",
                )),
                valid_markers: $markers,
            }
        }
    };
}

const EXPERIMENTAL_MARKERS: &[DataMarkerInfo] = &[
    icu_experimental::dimension::provider::currency::essentials::CurrencyEssentialsV1::INFO,
    icu_experimental::dimension::provider::currency::fractions::CurrencyFractionsV1::INFO,
    icu_experimental::dimension::provider::percent::PercentEssentialsV1::INFO,
    icu_experimental::dimension::provider::units::display_names::UnitsDisplayNamesV1::INFO,
    icu_experimental::dimension::provider::units::essentials::UnitsEssentialsV1::INFO,
    icu_experimental::relativetime::provider::LongDayRelativeV1::INFO,
    icu_experimental::relativetime::provider::LongHourRelativeV1::INFO,
    icu_experimental::relativetime::provider::LongMinuteRelativeV1::INFO,
    icu_experimental::relativetime::provider::LongMonthRelativeV1::INFO,
    icu_experimental::relativetime::provider::LongQuarterRelativeV1::INFO,
    icu_experimental::relativetime::provider::LongSecondRelativeV1::INFO,
    icu_experimental::relativetime::provider::LongWeekRelativeV1::INFO,
    icu_experimental::relativetime::provider::LongYearRelativeV1::INFO,
    icu_experimental::relativetime::provider::NarrowDayRelativeV1::INFO,
    icu_experimental::relativetime::provider::NarrowHourRelativeV1::INFO,
    icu_experimental::relativetime::provider::NarrowMinuteRelativeV1::INFO,
    icu_experimental::relativetime::provider::NarrowMonthRelativeV1::INFO,
    icu_experimental::relativetime::provider::NarrowQuarterRelativeV1::INFO,
    icu_experimental::relativetime::provider::NarrowSecondRelativeV1::INFO,
    icu_experimental::relativetime::provider::NarrowWeekRelativeV1::INFO,
    icu_experimental::relativetime::provider::NarrowYearRelativeV1::INFO,
    icu_experimental::relativetime::provider::ShortDayRelativeV1::INFO,
    icu_experimental::relativetime::provider::ShortHourRelativeV1::INFO,
    icu_experimental::relativetime::provider::ShortMinuteRelativeV1::INFO,
    icu_experimental::relativetime::provider::ShortMonthRelativeV1::INFO,
    icu_experimental::relativetime::provider::ShortQuarterRelativeV1::INFO,
    icu_experimental::relativetime::provider::ShortSecondRelativeV1::INFO,
    icu_experimental::relativetime::provider::ShortWeekRelativeV1::INFO,
    icu_experimental::relativetime::provider::ShortYearRelativeV1::INFO,
];

/// Boa's default buffer provider.
static PROVIDER: Lazy<LocaleFallbackProvider<MultiForkByMarkerProvider<LazyBufferProvider>>> =
    Lazy::new(|| {
        let provider = MultiForkByMarkerProvider::new(alloc::vec![
            provider_from_icu_crate!(icu_casemap),
            provider_from_icu_crate!(icu_collator),
            provider_from_icu_crate!(icu_datetime),
            provider_from_icu_crate!(icu_time),
            provider_from_icu_crate!(icu_decimal),
            provider_from_icu_crate!(icu_experimental, EXPERIMENTAL_MARKERS),
            provider_from_icu_crate!(icu_list),
            provider_from_icu_crate!(icu_locale),
            provider_from_icu_crate!(icu_normalizer),
            provider_from_icu_crate!(icu_plurals),
            provider_from_icu_crate!(icu_segmenter),
            provider_from_icu_crate!(boa_icu_data, boa_icu_data::MARKERS),
        ]);
        let fallbacker = LocaleFallbacker::try_new_with_buffer_provider(&provider)
            .expect("The statically compiled data file should be valid.");
        LocaleFallbackProvider::new(provider, fallbacker)
    });

#[derive(Debug)]
struct Wrapper<T: 'static>(&'static T);

impl<T> DynamicDataProvider<BufferMarker> for Wrapper<T>
where
    T: DynamicDataProvider<BufferMarker>,
{
    fn load_data(
        &self,
        marker: DataMarkerInfo,
        req: DataRequest<'_>,
    ) -> Result<DataResponse<BufferMarker>, DataError> {
        self.0.load_data(marker, req)
    }
}

impl<T> DynamicDryDataProvider<BufferMarker> for Wrapper<T>
where
    T: DynamicDryDataProvider<BufferMarker>,
{
    fn dry_load_data(
        &self,
        marker: DataMarkerInfo,
        req: DataRequest<'_>,
    ) -> Result<DataResponseMetadata, DataError> {
        self.0.dry_load_data(marker, req)
    }
}

/// Gets the default data provider stored as a [`DynamicDryDataProvider<BufferMarker>`].
///
/// [`DynamicDryDataProvider<BufferMarker>`]: icu_provider::DynamicDryDataProvider
#[must_use]
pub fn buffer() -> impl DynamicDryDataProvider<BufferMarker> {
    Wrapper(&*PROVIDER)
}

#[cfg(test)]
mod tests {
    use boa_icu_data::{BoaCurrencyAccountingPatternsV1, BoaNumberSpecialSymbolsV2};
    use icu_decimal::provider::DecimalDigitsV1;
    use icu_provider::prelude::*;

    #[test]
    fn bundled_provider_includes_explicit_numbering_system_digits() {
        let provider = super::buffer();
        for numbering_system in ["ahom", "mathsans", "wcho"] {
            let attributes = DataMarkerAttributes::try_from_str(numbering_system).unwrap();
            provider
                .load_data(
                    DecimalDigitsV1::INFO,
                    DataRequest {
                        id: DataIdentifierBorrowed::for_marker_attributes(attributes),
                        ..DataRequest::default()
                    },
                )
                .unwrap_or_else(|error| {
                    panic!("missing digits for numbering system {numbering_system}: {error}")
                });
        }
    }

    #[test]
    fn bundled_provider_includes_supplemental_number_symbols() {
        let provider = super::buffer();
        let locale = "zh-Hant".parse().unwrap();
        let numbering_system = DataMarkerAttributes::try_from_str("latn").unwrap();
        let response: DataResponse<BoaNumberSpecialSymbolsV2> = provider
            .as_deserializing()
            .load(DataRequest {
                id: DataIdentifierBorrowed::for_marker_attributes_and_locale(
                    numbering_system,
                    &locale,
                ),
                ..DataRequest::default()
            })
            .unwrap();
        assert_eq!(response.payload.get().nan, "非數值");
    }

    #[test]
    fn bundled_provider_includes_accounting_patterns() {
        let provider = super::buffer();
        let locale = "en".parse().unwrap();
        let response: DataResponse<BoaCurrencyAccountingPatternsV1> = provider
            .as_deserializing()
            .load(DataRequest {
                id: DataIdentifierBorrowed::for_locale(&locale),
                ..DataRequest::default()
            })
            .unwrap();
        let standard = response.payload.get().standard.as_ref().unwrap();
        assert_eq!((&*standard.prefix, &*standard.suffix), ("(", ")"));
    }

    #[test]
    fn bundled_provider_includes_every_relative_time_width_and_unit() {
        let provider = super::buffer();
        let locale = "nb".parse().unwrap();
        // The five dimension markers lead the table; the remaining 24 are
        // relative-time data (three widths for each of eight units).
        let relative_time_markers = &super::EXPERIMENTAL_MARKERS[5..];
        let mut loaded = 0;
        for marker in relative_time_markers {
            provider
                .load_data(
                    *marker,
                    DataRequest {
                        id: DataIdentifierBorrowed::for_locale(&locale),
                        ..DataRequest::default()
                    },
                )
                .unwrap_or_else(|error| panic!("missing {marker:?} for nb: {error}"));
            loaded += 1;
        }
        assert_eq!(loaded, 24);
    }
}
